name: Colorado Custom Carves
favicon: null
layout_spectrum: 1
typography_spectrum: 0.71061
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#181049'
    - '#ed2027'
    - '#fcee21'
    - '#bfb32b'
    - '#6a6522'
  brandStrength: 0.25
  lightness: 0.1875
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
